"""empty message

Revision ID: 67cf0d0e66ad
Revises: 6d7c693dd718
Create Date: 2025-03-20 13:17:09.232645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67cf0d0e66ad'
down_revision: Union[str, None] = '6d7c693dd718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('mail', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('join_data', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_time_login', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
